#!/usr/bin/env python3

# Define function ...
def tagId2tagName(
    tagId,
    /,
    *,
    debug = __debug__,
      gps = False,
):
    """Match tag ID number to tag name.

    Parameters
    ----------
    tagId : int
        The tag ID number.
    debug : bool, optional
        Print debug messages.
    gps : bool, optional
        Is this directory GPS metadata?

    Returns
    -------
    tagName : str
        The tag name.

    Notes
    -----
    Copyright 2017 Thomas Guymer [1]_

    References
    ----------
    .. [1] PyGuymer3, https://github.com/Guymer/PyGuymer3
    """

    # Check if this is a GPS tag ID ...
    if gps:
        # Match the GPS tag ID with its name ...
        # NOTE: See Section 5.2.45 (pages 37 & 38) of N4378.pdf
        # NOTE: See https://web.archive.org/web/20180921145139if_/http://www.cipa.jp:80/std/documents/e/DC-010-2017_E.pdf
        # NOTE: See https://exiv2.org/tags.html
        match tagId:
            case 0:
                return "GPSVersionID"
            case 1:
                return "GPSLatitudeRef"
            case 2:
                return "GPSLatitude"
            case 3:
                return "GPSLongitudeRef"
            case 4:
                return "GPSLongitude"
            case 5:
                return "GPSAltitudeRef"
            case 6:
                return "GPSAltitude"
            case 7:
                return "GPSTimeStamp"
            case 8:
                return "GPSSatellites"
            case 9:
                return "GPSStatus"
            case 10:
                return "GPSMeasureMode"
            case 11:
                return "GPSDOP"
            case 12:
                return "GPSSpeedRef"
            case 13:
                return "GPSSpeed"
            case 14:
                return "GPSTrackRef"
            case 15:
                return "GPSTrack"
            case 16:
                return "GPSImgDirectionRef"
            case 17:
                return "GPSImgDirection"
            case 18:
                return "GPSMapDatum"
            case 19:
                return "GPSDestLatitudeRef"
            case 20:
                return "GPSDestLatitude"
            case 21:
                return "GPSDestLongitudeRef"
            case 22:
                return "GPSDestLongitude"
            case 23:
                return "GPSDestBearingRef"
            case 24:
                return "GPSDestBearing"
            case 25:
                return "GPSDestDistanceRef"
            case 26:
                return "GPSDestDistance"
            case 27:
                return "GPSProcessingMethod"
            case 28:
                return "GPSAreaInformation"
            case 29:
                return "GPSDateStamp"
            case 30:
                return "GPSDifferential"
            case 31:
                return "GPSHPositioningError"
            case _:
                if debug:
                    print(f"DEBUG: {tagId:d} is not in Section 5.2.45 of \"N4378.pdf\"")
                return None

    # Match the tag ID with its name ...
    # NOTE: See Table 1 (pages 17-19) of N4378.pdf
    # NOTE: See https://web.archive.org/web/20180921145139if_/http://www.cipa.jp:80/std/documents/e/DC-010-2017_E.pdf
    # NOTE: See https://exiv2.org/tags.html
    match tagId:
        case 11:
            return "ProcessingSoftware"
        case 254:
            return "NewSubfileType"
        case 255:
            return "SubfileType"
        case 256:
            return "ImageWidth"
        case 257:
            return "ImageLength"
        case 258:
            return "BitsPerSample"
        case 259:
            return "Compression"
        case 262:
            return "PhotometricInterpretation"
        case 263:
            return "Thresholding"
        case 264:
            return "CellWidth"
        case 265:
            return "CellLength"
        case 266:
            return "FillOrder"
        case 269:
            return "DocumentName"
        case 270:
            return "ImageDescription"
        case 271:
            return "Make"
        case 272:
            return "Model"
        case 273:
            return "StripOffsets"
        case 274:
            return "Orientation"
        case 277:
            return "SamplesPerPixel"
        case 278:
            return "RowsPerStrip"
        case 279:
            return "StripByteCounts"
        case 282:
            return "XResolution"
        case 283:
            return "YResolution"
        case 284:
            return "PlanarConfiguration"
        case 285:
            return "PageName"
        case 286:
            return "XPosition"
        case 287:
            return "YPosition"
        case 290:
            return "GrayResponseUnit"
        case 291:
            return "GrayResponseCurve"
        case 292:
            return "T4Options"
        case 293:
            return "T6Options"
        case 296:
            return "ResolutionUnit"
        case 297:
            return "PageNumber"
        case 301:
            return "TransferFunction"
        case 305:
            return "Software"
        case 306:
            return "DateTime"
        case 315:
            return "Artist"
        case 316:
            return "HostComputer"
        case 317:
            return "Predictor"
        case 318:
            return "WhitePoint"
        case 319:
            return "PrimaryChromaticities"
        case 320:
            return "ColorMap"
        case 321:
            return "HalftoneHints"
        case 322:
            return "TileWidth"
        case 323:
            return "TileLength"
        case 324:
            return "TileOffsets"
        case 325:
            return "TileByteCounts"
        case 330:
            return "SubIFDs"
        case 332:
            return "InkSet"
        case 333:
            return "InkNames"
        case 334:
            return "NumberOfInks"
        case 336:
            return "DotRange"
        case 337:
            return "TargetPrinter"
        case 338:
            return "ExtraSamples"
        case 339:
            return "SampleFormat"
        case 340:
            return "SMinSampleValue"
        case 341:
            return "SMaxSampleValue"
        case 342:
            return "TransferRange"
        case 343:
            return "ClipPath"
        case 344:
            return "XClipPathUnits"
        case 345:
            return "YClipPathUnits"
        case 346:
            return "Indexed"
        case 347:
            return "JPEGTables"
        case 351:
            return "OPIProxy"
        case 512:
            return "JPEGProc"
        case 513:
            return "JPEGInterchangeFormat"
        case 514:
            return "JPEGInterchangeFormatLength"
        case 515:
            return "JPEGRestartInterval"
        case 517:
            return "JPEGLosslessPredictors"
        case 518:
            return "JPEGPointTransforms"
        case 519:
            return "JPEGQTables"
        case 520:
            return "JPEGDCTables"
        case 521:
            return "JPEGACTables"
        case 529:
            return "YCbCrCoefficients"
        case 530:
            return "YCbCrSubSampling"
        case 531:
            return "YCbCrPositioning"
        case 532:
            return "ReferenceBlackWhite"
        case 700:
            return "XMLPacket"
        case 18246:
            return "Rating"
        case 18249:
            return "RatingPercent"
        case 28722:
            return "VignettingCorrParams"
        case 28725:
            return "ChromaticAberrationCorrParams"
        case 28727:
            return "DistortionCorrParams"
        case 32781:
            return "ImageID"
        case 33421:
            return "CFARepeatPatternDim"
        case 33422:
            return "CFAPattern"
        case 33423:
            return "BatteryLevel"
        case 33432:
            return "Copyright"
        case 33434:
            return "ExposureTime"
        case 33437:
            return "FNumber"
        case 33723:
            return "IPTCNAA"
        case 34377:
            return "ImageResources"
        case 34665:
            return "ExifTag"
        case 34675:
            return "InterColorProfile"
        case 34850:
            return "ExposureProgram"
        case 34852:
            return "SpectralSensitivity"
        case 34853:
            return "GPSTag"
        case 34855:
            return "ISOSpeedRatings"
        case 34856:
            return "OECF"
        case 34857:
            return "Interlace"
        case 34858:
            return "TimeZoneOffset"
        case 34859:
            return "SelfTimerMode"
        case 34864:
            return "SensitivityType"
        case 34865:
            return "StandardOutputSensitivity"
        case 34866:
            return "RecommendedExposureIndex"
        case 34867:
            return "ISOSpeed"
        case 34868:
            return "ISOSpeedLatitudeyyy"
        case 34869:
            return "ISOSpeedLatitudezzz"
        case 36864:
            return "ExifVersion"
        case 36867:
            return "DateTimeOriginal"
        case 36868:
            return "DateTimeDigitized"
        case 36880:
            return "OffsetTime"
        case 36881:
            return "OffsetTimeOriginal"
        case 36882:
            return "OffsetTimeDigitized"
        case 37121:
            return "ComponentsConfiguration"
        case 37122:
            return "CompressedBitsPerPixel"
        case 37377:
            return "ShutterSpeedValue"
        case 37378:
            return "ApertureValue"
        case 37379:
            return "BrightnessValue"
        case 37380:
            return "ExposureBiasValue"
        case 37381:
            return "MaxApertureValue"
        case 37382:
            return "SubjectDistance"
        case 37383:
            return "MeteringMode"
        case 37384:
            return "LightSource"
        case 37385:
            return "Flash"
        case 37386:
            return "FocalLength"
        case 37387:
            return "FlashEnergy"
        case 37388:
            return "SpatialFrequencyResponse"
        case 37389:
            return "Noise"
        case 37390:
            return "FocalPlaneXResolution"
        case 37391:
            return "FocalPlaneYResolution"
        case 37392:
            return "FocalPlaneResolutionUnit"
        case 37393:
            return "ImageNumber"
        case 37394:
            return "SecurityClassification"
        case 37395:
            return "ImageHistory"
        case 37396:
            return "SubjectArea"
        case 37397:
            return "ExposureIndex"
        case 37398:
            return "TIFFEPStandardID"
        case 37399:
            return "SensingMethod"
        case 37500:
            return "MakerNote"
        case 37510:
            return "UserComment"
        case 37520:
            return "SubSecTime"
        case 37521:
            return "SubSecTimeOriginal"
        case 37522:
            return "SubSecTimeDigitized"
        case 37888:
            return "Temperature"
        case 37889:
            return "Humidity"
        case 37890:
            return "Pressure"
        case 37891:
            return "WaterDepth"
        case 37892:
            return "Acceleration"
        case 37893:
            return "CameraElevationAngle"
        case 40091:
            return "XPTitle"
        case 40092:
            return "XPComment"
        case 40093:
            return "XPAuthor"
        case 40094:
            return "XPKeywords"
        case 40095:
            return "XPSubject"
        case 40960:
            return "FlashpixVersion"
        case 40961:
            return "ColorSpace"
        case 40962:
            return "PixelXDimension"
        case 40963:
            return "PixelYDimension"
        case 40964:
            return "RelatedSoundFile"
        case 40965:
            return "InteroperabilityTag"
        case 41483:
            return "FlashEnergy"
        case 41484:
            return "SpatialFrequencyResponse"
        case 41486:
            return "FocalPlaneXResolution"
        case 41487:
            return "FocalPlaneYResolution"
        case 41488:
            return "FocalPlaneResolutionUnit"
        case 41492:
            return "SubjectLocation"
        case 41493:
            return "ExposureIndex"
        case 41495:
            return "SensingMethod"
        case 41728:
            return "FileSource"
        case 41729:
            return "SceneType"
        case 41730:
            return "CFAPattern"
        case 41985:
            return "CustomRendered"
        case 41986:
            return "ExposureMode"
        case 41987:
            return "WhiteBalance"
        case 41988:
            return "DigitalZoomRatio"
        case 41989:
            return "FocalLengthIn35mmFilm"
        case 41990:
            return "SceneCaptureType"
        case 41991:
            return "GainControl"
        case 41992:
            return "Contrast"
        case 41993:
            return "Saturation"
        case 41994:
            return "Sharpness"
        case 41995:
            return "DeviceSettingDescription"
        case 41996:
            return "SubjectDistanceRange"
        case 42016:
            return "ImageUniqueID"
        case 42032:
            return "CameraOwnerName"
        case 42033:
            return "BodySerialNumber"
        case 42034:
            return "LensSpecification"
        case 42035:
            return "LensMake"
        case 42036:
            return "LensModel"
        case 42037:
            return "LensSerialNumber"
        case 42038:
            return "ImageTitle"
        case 42039:
            return "Photographer"
        case 42040:
            return "ImageEditor"
        case 42041:
            return "CameraFirmware"
        case 42042:
            return "RAWDevelopingSoftware"
        case 42043:
            return "ImageEditingSoftware"
        case 42044:
            return "MetadataEditingSoftware"
        case 42080:
            return "CompositeImage"
        case 42081:
            return "SourceImageNumberOfCompositeImage"
        case 42082:
            return "SourceExposureTimesOfCompositeImage"
        case 42240:
            return "Gamma"
        case 50341:
            return "PrintImageMatching"
        case 50706:
            return "DNGVersion"
        case 50707:
            return "DNGBackwardVersion"
        case 50708:
            return "UniqueCameraModel"
        case 50709:
            return "LocalizedCameraModel"
        case 50710:
            return "CFAPlaneColor"
        case 50711:
            return "CFALayout"
        case 50712:
            return "LinearizationTable"
        case 50713:
            return "BlackLevelRepeatDim"
        case 50714:
            return "BlackLevel"
        case 50715:
            return "BlackLevelDeltaH"
        case 50716:
            return "BlackLevelDeltaV"
        case 50717:
            return "WhiteLevel"
        case 50718:
            return "DefaultScale"
        case 50719:
            return "DefaultCropOrigin"
        case 50720:
            return "DefaultCropSize"
        case 50721:
            return "ColorMatrix1"
        case 50722:
            return "ColorMatrix2"
        case 50723:
            return "CameraCalibration1"
        case 50724:
            return "CameraCalibration2"
        case 50725:
            return "ReductionMatrix1"
        case 50726:
            return "ReductionMatrix2"
        case 50727:
            return "AnalogBalance"
        case 50728:
            return "AsShotNeutral"
        case 50729:
            return "AsShotWhiteXY"
        case 50730:
            return "BaselineExposure"
        case 50731:
            return "BaselineNoise"
        case 50732:
            return "BaselineSharpness"
        case 50733:
            return "BayerGreenSplit"
        case 50734:
            return "LinearResponseLimit"
        case 50735:
            return "CameraSerialNumber"
        case 50736:
            return "LensInfo"
        case 50737:
            return "ChromaBlurRadius"
        case 50738:
            return "AntiAliasStrength"
        case 50739:
            return "ShadowScale"
        case 50740:
            return "DNGPrivateData"
        case 50741:
            return "MakerNoteSafety"
        case 50778:
            return "CalibrationIlluminant1"
        case 50779:
            return "CalibrationIlluminant2"
        case 50780:
            return "BestQualityScale"
        case 50781:
            return "RawDataUniqueID"
        case 50827:
            return "OriginalRawFileName"
        case 50828:
            return "OriginalRawFileData"
        case 50829:
            return "ActiveArea"
        case 50830:
            return "MaskedAreas"
        case 50831:
            return "AsShotICCProfile"
        case 50832:
            return "AsShotPreProfileMatrix"
        case 50833:
            return "CurrentICCProfile"
        case 50834:
            return "CurrentPreProfileMatrix"
        case 50879:
            return "ColorimetricReference"
        case 50931:
            return "CameraCalibrationSignature"
        case 50932:
            return "ProfileCalibrationSignature"
        case 50933:
            return "ExtraCameraProfiles"
        case 50934:
            return "AsShotProfileName"
        case 50935:
            return "NoiseReductionApplied"
        case 50936:
            return "ProfileName"
        case 50937:
            return "ProfileHueSatMapDims"
        case 50938:
            return "ProfileHueSatMapData1"
        case 50939:
            return "ProfileHueSatMapData2"
        case 50940:
            return "ProfileToneCurve"
        case 50941:
            return "ProfileEmbedPolicy"
        case 50942:
            return "ProfileCopyright"
        case 50964:
            return "ForwardMatrix1"
        case 50965:
            return "ForwardMatrix2"
        case 50966:
            return "PreviewApplicationName"
        case 50967:
            return "PreviewApplicationVersion"
        case 50968:
            return "PreviewSettingsName"
        case 50969:
            return "PreviewSettingsDigest"
        case 50970:
            return "PreviewColorSpace"
        case 50971:
            return "PreviewDateTime"
        case 50972:
            return "RawImageDigest"
        case 50973:
            return "OriginalRawFileDigest"
        case 50974:
            return "SubTileBlockSize"
        case 50975:
            return "RowInterleaveFactor"
        case 50981:
            return "ProfileLookTableDims"
        case 50982:
            return "ProfileLookTableData"
        case 51008:
            return "OpcodeList1"
        case 51009:
            return "OpcodeList2"
        case 51022:
            return "OpcodeList3"
        case 51041:
            return "NoiseProfile"
        case 51043:
            return "TimeCodes"
        case 51044:
            return "FrameRate"
        case 51058:
            return "TStop"
        case 51081:
            return "ReelName"
        case 51089:
            return "OriginalDefaultFinalSize"
        case 51090:
            return "OriginalBestQualityFinalSize"
        case 51091:
            return "OriginalDefaultCropSize"
        case 51105:
            return "CameraLabel"
        case 51107:
            return "ProfileHueSatMapEncoding"
        case 51108:
            return "ProfileLookTableEncoding"
        case 51109:
            return "BaselineExposureOffset"
        case 51110:
            return "DefaultBlackRender"
        case 51111:
            return "NewRawImageDigest"
        case 51112:
            return "RawToPreviewGain"
        case 51125:
            return "DefaultUserCrop"
        case 51177:
            return "DepthFormat"
        case 51178:
            return "DepthNear"
        case 51179:
            return "DepthFar"
        case 51180:
            return "DepthUnits"
        case 51181:
            return "DepthMeasureType"
        case 51182:
            return "EnhanceParams"
        case 52525:
            return "ProfileGainTableMap"
        case 52526:
            return "SemanticName"
        case 52528:
            return "SemanticInstanceID"
        case 52529:
            return "CalibrationIlluminant3"
        case 52530:
            return "CameraCalibration3"
        case 52531:
            return "ColorMatrix3"
        case 52532:
            return "ForwardMatrix3"
        case 52533:
            return "IlluminantData1"
        case 52534:
            return "IlluminantData2"
        case 52535:
            return "IlluminantData3"
        case 52536:
            return "MaskSubArea"
        case 52537:
            return "ProfileHueSatMapData3"
        case 52538:
            return "ReductionMatrix3"
        case 52543:
            return "RGBTables"
        case 52544:
            return "ProfileGainTableMap2"
        case 52547:
            return "ColumnInterleaveFactor"
        case 52548:
            return "ImageSequenceInfo"
        case 52550:
            return "ImageStats"
        case 52551:
            return "ProfileDynamicRange"
        case 52552:
            return "ProfileGroupName"
        case 52553:
            return "JXLDistance"
        case 52554:
            return "JXLEffort"
        case 52555:
            return "JXLDecodeSpeed"
        case _:
            if debug:
                print(f"DEBUG: {tagId:d} is not in Table 1 of \"N4378.pdf\"")
            return None
