# See https://github.com/readthedocs/readthedocs.org/issues/10290#issuecomment-1535120995

version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.11"
    jobs:
        post_install:
            - which python3
            - which f2py
            - which gfortran
            - gmake -r -C pyguymer3/f90 FC1=f2py FC2=gfortran PYTHON3=python3

python:
    install:
        - requirements: docs/requirements.txt
