# See https://github.com/readthedocs/readthedocs.org/issues/10290#issuecomment-1535120995

version: 2

build:
    apt_packages:
        - gfortran-12
    jobs:
        post_install:
            - which f2py
            - which gfortran-12
            - which python3
            - gmake -r -C pyguymer3/f90 FC1=/home/docs/checkouts/readthedocs.org/user_builds/pyguymer3/envs/latest/bin/f2py FC2=gfortran PYTHON3=/home/docs/checkouts/readthedocs.org/user_builds/pyguymer3/envs/latest/bin/python3
    os: ubuntu-22.04
    tools:
        python: "3.11"

python:
    install:
        - requirements: docs/requirements.txt
