# NOTE: The "os" must be specified to work around a library incompatibility in
#       the default one, see:
#         * https://github.com/readthedocs/readthedocs.org/issues/10290

version: 2

build:
    apt_packages:
        - gfortran-12
        - meson
    jobs:
        post_install:
            - which f2py
            - which gfortran-12
            - which gmake
            - which meson
            - which pip3
            - which python3
            - gmake -r -C pyguymer3/f90 FC1=`which f2py` FC2=`which gfortran-12` PYTHON3=`which python3`
    os: ubuntu-22.04
    tools:
        python: "3.11"

python:
    install:
        - requirements: requirements.txt
        - requirements: docs/requirements.txt
        - requirements: pyguymer3/f90/fortranlib/requirements.txt

submodules:
    include: all
    recursive: true
