# See https://github.com/readthedocs/readthedocs.org/issues/10290#issuecomment-1535120995

version: 2

build:
    apt_packages:
        - gfortran-12
    jobs:
        post_install:
            - which f2py
            - which gfortran-12
            - which python3
            - gmake -r -C pyguymer3/f90 FC1=`which f2py` FC2=`which gfortran-12` PYTHON3=`which python3`
    os: ubuntu-22.04
    tools:
        python: "3.11"

python:
    install:
        - requirements: docs/requirements.txt
