def load_EXIF(fname, kwArgCheck = None, python = True):
    # Load sub-functions ...
    from .load_EXIF1 import load_EXIF1
    from .load_EXIF2 import load_EXIF2

    # Check keyword arguments ...
    if kwArgCheck is not None:
        print(f"WARNING: \"{__name__}\" has been called with an extra positional argument")

    # Check what the user wants ...
    if python:
        # Will use the Python module "exifread" ...
        return load_EXIF1(fname)
    else:
        # Will use the binary "exiftool" ...
        return load_EXIF2(fname)
