#!/usr/bin/env python3

# Define function ...
def checkSudokuBoard(board, /):
    # Loop over numbers ...
    for num in range(1, 10):
        # Loop over columns ...
        for iy in range(9):
            # Check that the number is not in the row more than once ...
            if (board[iy, :] == num).sum() > 1:
                # Return answer ...
                return False

        # Loop over rows ...
        for ix in range(9):
            # Check that the number is not in the column more than once ...
            if (board[:, ix] == num).sum() > 1:
                # Return answer ...
                return False

        # Loop over y-squares ...
        for sy in range(3):
            # Loop over x-squares ...
            for sx in range(3):
                # Check that the number is not in the square more than once ...
                if (board[sy * 3:(sy + 1) * 3, sx * 3:(sx + 1) * 3] == num).sum() > 1:
                    # Return answer ...
                    return False

    # Return answer ...
    return True
