#!/usr/bin/env python3

# Define function ...
def hostname():
    # Import standard modules ...
    import socket

    # Get (potentially fully-qualified) hostname and return the first part ...
    return socket.gethostname().split(".")[0]
