#!/usr/bin/env python3

# Define function ...
def make_path_safe(path):
    # Loop over bad characters ...
    for badChar in ["\\", "/", ":", "*", "?", "\"", "<", ">", "|", "%", "#", "$"]:
        # Remove bad character ...
        path = path.replace(badChar, "")

    # Check if the path is empty ...
    if len(path) == 0:
        raise Exception("\"path\" does not contain any good characters") from None

    # Check if the path is hidden ...
    if path[0] == ".":
        # Make the path visible ...
        path = f" {path}"

    # Return answer ...
    return path
