def make_path_safe(path):
    # Loop over bad characters ...
    for badChar in ["\\", "/", ":", "*", "?", "\"", "<", ">", "|", "%", "#", "$"]:
        # Remove bad character ...
        path = path.replace(badChar, "")

    # Check if the path is hidden ...
    if path[0] == ".":
        # Make the path visible ...
        path = f" {path}"

    # Return answer ...
    return path
